@extends("pages.layouts.app")

@section("content")
    @include('pages.layouts.partials.slider')
    @include('pages.layouts.partials.services')
    @include('pages.layouts.partials.fancy-box')
    @include('pages.layouts.partials.quote-tab')
    @include('pages.layouts.partials.testimonials')
    @include('pages.layouts.partials.partners')
    @include('pages.layouts.partials.banner')
    @include('pages.layouts.partials.project-card')
    @include('pages.layouts.partials.banner-one')
    @include('pages.layouts.partials.blog-grid')
    @include('pages.layouts.partials.contact-card')
@endsection
